export const elements = [
  { symbol: 'H', name: 'Hydrogen', number: 1, xpos: 1, ypos: 1, category: 'nonmetal', atomic_mass: 1.008 },
  { symbol: 'He', name: 'Helium', number: 2, xpos: 18, ypos: 1, category: 'noble gas', atomic_mass: 4.003 },
  { symbol: 'Li', name: 'Lithium', number: 3, xpos: 1, ypos: 2, category: 'alkali metal', atomic_mass: 6.94 },
  { symbol: 'Be', name: 'Beryllium', number: 4, xpos: 2, ypos: 2, category: 'alkaline earth metal', atomic_mass: 9.012 },
  { symbol: 'B', name: 'Boron', number: 5, xpos: 13, ypos: 2, category: 'metalloid', atomic_mass: 10.81 },
  { symbol: 'C', name: 'Carbon', number: 6, xpos: 14, ypos: 2, category: 'nonmetal', atomic_mass: 12.01 },
  { symbol: 'N', name: 'Nitrogen', number: 7, xpos: 15, ypos: 2, category: 'nonmetal', atomic_mass: 14.01 },
  { symbol: 'O', name: 'Oxygen', number: 8, xpos: 16, ypos: 2, category: 'nonmetal', atomic_mass: 16.00 },
  { symbol: 'F', name: 'Fluorine', number: 9, xpos: 17, ypos: 2, category: 'nonmetal', atomic_mass: 18.99 },
  { symbol: 'Ne', name: 'Neon', number: 10, xpos: 18, ypos: 2, category: 'noble gas', atomic_mass: 20.18 },
  { symbol: 'Na', name: 'Sodium', number: 11, xpos: 1, ypos: 3, category: 'alkali metal', atomic_mass: 22.99 },
  { symbol: 'Mg', name: 'Magnesium', number: 12, xpos: 2, ypos: 3, category: 'alkaline earth metal', atomic_mass: 24.31 },
  { symbol: 'Al', name: 'Aluminum', number: 13, xpos: 13, ypos: 3, category: 'post-transition metal', atomic_mass: 26.98 },
  { symbol: 'Si', name: 'Silicon', number: 14, xpos: 14, ypos: 3, category: 'metalloid', atomic_mass: 28.09 },
  { symbol: 'P', name: 'Phosphorus', number: 15, xpos: 15, ypos: 3, category: 'nonmetal', atomic_mass: 30.97 },
  { symbol: 'S', name: 'Sulfur', number: 16, xpos: 16, ypos: 3, category: 'nonmetal', atomic_mass: 32.06 },
  { symbol: 'Cl', name: 'Chlorine', number: 17, xpos: 17, ypos: 3, category: 'nonmetal', atomic_mass: 35.45 },
  { symbol: 'Ar', name: 'Argon', number: 18, xpos: 18, ypos: 3, category: 'noble gas', atomic_mass: 39.95 },
  { symbol: 'K', name: 'Potassium', number: 19, xpos: 1, ypos: 4, category: 'alkali metal', atomic_mass: 39.10 },
  { symbol: 'Ca', name: 'Calcium', number: 20, xpos: 2, ypos: 4, category: 'alkaline earth metal', atomic_mass: 40.08 },
  { symbol: 'Sc', name: 'Scandium', number: 21, xpos: 3, ypos: 4, category: 'transition metal', atomic_mass: 44.96 },
  { symbol: 'Ti', name: 'Titanium', number: 22, xpos: 4, ypos: 4, category: 'transition metal', atomic_mass: 47.87 },
  { symbol: 'V', name: 'Vanadium', number: 23, xpos: 5, ypos: 4, category: 'transition metal', atomic_mass: 50.94 },
  { symbol: 'Cr', name: 'Chromium', number: 24, xpos: 6, ypos: 4, category: 'transition metal', atomic_mass: 51.99 },
  { symbol: 'Mn', name: 'Manganese', number: 25, xpos: 7, ypos: 4, category: 'transition metal', atomic_mass: 54.94 },
  { symbol: 'Fe', name: 'Iron', number: 26, xpos: 8, ypos: 4, category: 'transition metal', atomic_mass: 55.85 },
  { symbol: 'Co', name: 'Cobalt', number: 27, xpos: 9, ypos: 4, category: 'transition metal', atomic_mass: 58.93 },
  { symbol: 'Ni', name: 'Nickel', number: 28, xpos: 10, ypos: 4, category: 'transition metal', atomic_mass: 58.69 },
  { symbol: 'Cu', name: 'Copper', number: 29, xpos: 11, ypos: 4, category: 'transition metal', atomic_mass: 63.55 },
  { symbol: 'Zn', name: 'Zinc', number: 30, xpos: 12, ypos: 4, category: 'transition metal', atomic_mass: 65.38 },
  { symbol: 'Ga', name: 'Gallium', number: 31, xpos: 13, ypos: 4, category: 'post-transition metal', atomic_mass: 69.72 },
  { symbol: 'Ge', name: 'Germanium', number: 32, xpos: 14, ypos: 4, category: 'metalloid', atomic_mass: 72.63 },
  { symbol: 'As', name: 'Arsenic', number: 33, xpos: 15, ypos: 4, category: 'metalloid', atomic_mass: 74.92 },
  { symbol: 'Se', name: 'Selenium', number: 34, xpos: 16, ypos: 4, category: 'nonmetal', atomic_mass: 78.97 },
  { symbol: 'Br', name: 'Bromine', number: 35, xpos: 17, ypos: 4, category: 'nonmetal', atomic_mass: 79.90 },
  { symbol: 'Kr', name: 'Krypton', number: 36, xpos: 18, ypos: 4, category: 'noble gas', atomic_mass: 83.80 },
  { symbol: 'Rb', name: 'Rubidium', number: 37, xpos: 1, ypos: 5, category: 'alkali metal', atomic_mass: 85.47 },
  { symbol: 'Sr', name: 'Strontium', number: 38, xpos: 2, ypos: 5, category: 'alkaline earth metal', atomic_mass: 87.62 },
  { symbol: 'Y', name: 'Yttrium', number: 39, xpos: 3, ypos: 5, category: 'transition metal', atomic_mass: 88.91 },
  { symbol: 'Zr', name: 'Zirconium', number: 40, xpos: 4, ypos: 5, category: 'transition metal', atomic_mass: 91.22 },
  { symbol: 'Nb', name: 'Niobium', number: 41, xpos: 5, ypos: 5, category: 'transition metal', atomic_mass: 92.91 },
  { symbol: 'Mo', name: 'Molybdenum', number: 42, xpos: 6, ypos: 5, category: 'transition metal', atomic_mass: 95.96 },
  { symbol: 'Tc', name: 'Technetium', number: 43, xpos: 7, ypos: 5, category: 'transition metal', atomic_mass: 98 },
  { symbol: 'Ru', name: 'Ruthenium', number: 44, xpos: 8, ypos: 5, category: 'transition metal', atomic_mass: 101.07 },
  { symbol: 'Rh', name: 'Rhodium', number: 45, xpos: 9, ypos: 5, category: 'transition metal', atomic_mass: 102.91 },
  { symbol: 'Pd', name: 'Palladium', number: 46, xpos: 10, ypos: 5, category: 'transition metal', atomic_mass: 106.42 },
  { symbol: 'Ag', name: 'Silver', number: 47, xpos: 11, ypos: 5, category: 'transition metal', atomic_mass: 107.87 },
  { symbol: 'Cd', name: 'Cadmium', number: 48, xpos: 12, ypos: 5, category: 'transition metal', atomic_mass: 112.41 },
  { symbol: 'In', name: 'Indium', number: 49, xpos: 13, ypos: 5, category: 'post-transition metal', atomic_mass: 114.82 },
  { symbol: 'Sn', name: 'Tin', number: 50, xpos: 14, ypos: 5, category: 'post-transition metal', atomic_mass: 118.71 },
  { symbol: 'Sb', name: 'Antimony', number: 51, xpos: 15, ypos: 5, category: 'metalloid', atomic_mass: 121.76 },
  { symbol: 'Te', name: 'Tellurium', number: 52, xpos: 16, ypos: 5, category: 'metalloid', atomic_mass: 127.60 },
  { symbol: 'I', name: 'Iodine', number: 53, xpos: 17, ypos: 5, category: 'nonmetal', atomic_mass: 126.90 },
  { symbol: 'Xe', name: 'Xenon', number: 54, xpos: 18, ypos: 5, category: 'noble gas', atomic_mass: 131.29 },
  { symbol: 'Cs', name: 'Cesium', number: 55, xpos: 1, ypos: 6, category: 'alkali metal', atomic_mass: 132.91 },
  { symbol: 'Ba', name: 'Barium', number: 56, xpos: 2, ypos: 6, category: 'alkaline earth metal', atomic_mass: 137.33 },
  { symbol: 'La', name: 'Lanthanum', number: 57, xpos: 3, ypos: 6, category: 'lanthanide', atomic_mass: 138.91 },
  { symbol: 'Ce', name: 'Cerium', number: 58, xpos: 4, ypos: 9, category: 'lanthanide', atomic_mass: 140.12 },
  { symbol: 'Pr', name: 'Praseodymium', number: 59, xpos: 5, ypos: 9, category: 'lanthanide', atomic_mass: 140.91 },
  { symbol: 'Nd', name: 'Neodymium', number: 60, xpos: 6, ypos: 9, category: 'lanthanide', atomic_mass: 144.24 },
  { symbol: 'Pm', name: 'Promethium', number: 61, xpos: 7, ypos: 9, category: 'lanthanide', atomic_mass: 145 },
  { symbol: 'Sm', name: 'Samarium', number: 62, xpos: 8, ypos: 9, category: 'lanthanide', atomic_mass: 150.36 },
  { symbol: 'Eu', name: 'Europium', number: 63, xpos: 9, ypos: 9, category: 'lanthanide', atomic_mass: 151.96 },
  { symbol: 'Gd', name: 'Gadolinium', number: 64, xpos: 10, ypos: 9, category: 'lanthanide', atomic_mass: 157.25 },
  { symbol: 'Tb', name: 'Terbium', number: 65, xpos: 11, ypos: 9, category: 'lanthanide', atomic_mass: 158.93 },
  { symbol: 'Dy', name: 'Dysprosium', number: 66, xpos: 12, ypos: 9, category: 'lanthanide', atomic_mass: 162.50 },
  { symbol: 'Ho', name: 'Holmium', number: 67, xpos: 13, ypos: 9, category: 'lanthanide', atomic_mass: 164.93 },
  { symbol: 'Er', name: 'Erbium', number: 68, xpos: 14, ypos: 9, category: 'lanthanide', atomic_mass: 167.26 },
  { symbol: 'Tm', name: 'Thulium', number: 69, xpos: 15, ypos: 9, category: 'lanthanide', atomic_mass: 168.93 },
  { symbol: 'Yb', name: 'Ytterbium', number: 70, xpos: 16, ypos: 9, category: 'lanthanide', atomic_mass: 173.05 },
  { symbol: 'Lu', name: 'Lutetium', number: 71, xpos: 17, ypos: 9, category: 'lanthanide', atomic_mass: 175.00 },
  { symbol: 'Hf', name: 'Hafnium', number: 72, xpos: 4, ypos: 6, category: 'transition metal', atomic_mass: 178.49 },
  { symbol: 'Ta', name: 'Tantalum', number: 73, xpos: 5, ypos: 6, category: 'transition metal', atomic_mass: 180.95 },
  { symbol: 'W', name: 'Tungsten', number: 74, xpos: 6, ypos: 6, category: 'transition metal', atomic_mass: 183.84 },
  { symbol: 'Re', name: 'Rhenium', number: 75, xpos: 7, ypos: 6, category: 'transition metal', atomic_mass: 186.21 },
  { symbol: 'Os', name: 'Osmium', number: 76, xpos: 8, ypos: 6, category: 'transition metal', atomic_mass: 190.23 },
  { symbol: 'Ir', name: 'Iridium', number: 77, xpos: 9, ypos: 6, category: 'transition metal', atomic_mass: 192.22 },
  { symbol: 'Pt', name: 'Platinum', number: 78, xpos: 10, ypos: 6, category: 'transition metal', atomic_mass: 195.08 },
  { symbol: 'Au', name: 'Gold', number: 79, xpos: 11, ypos: 6, category: 'transition metal', atomic_mass: 196.97 },
  { symbol: 'Hg', name: 'Mercury', number: 80, xpos: 12, ypos: 6, category: 'transition metal', atomic_mass: 200.59 },
  { symbol: 'Tl', name: 'Thallium', number: 81, xpos: 13, ypos: 6, category: 'post-transition metal', atomic_mass: 204.38 },
  { symbol: 'Pb', name: 'Lead', number: 82, xpos: 14, ypos: 6, category: 'post-transition metal', atomic_mass: 207.2 },
  { symbol: 'Bi', name: 'Bismuth', number: 83, xpos: 15, ypos: 6, category: 'post-transition metal', atomic_mass: 208.98 },
  { symbol: 'Po', name: 'Polonium', number: 84, xpos: 16, ypos: 6, category: 'post-transition metal', atomic_mass: 209 },
  { symbol: 'At', name: 'Astatine', number: 85, xpos: 17, ypos: 6, category: 'metalloid', atomic_mass: 210 },
  { symbol: 'Rn', name: 'Radon', number: 86, xpos: 18, ypos: 6, category: 'noble gas', atomic_mass: 222 },
  { symbol: 'Fr', name: 'Francium', number: 87, xpos: 1, ypos: 7, category: 'alkali metal', atomic_mass: 223 },
  { symbol: 'Ra', name: 'Radium', number: 88, xpos: 2, ypos: 7, category: 'alkaline earth metal', atomic_mass: 226 },
  { symbol: 'Ac', name: 'Actinium', number: 89, xpos: 3, ypos: 7, category: 'actinide', atomic_mass: 227 },
  { symbol: 'Th', name: 'Thorium', number: 90, xpos: 4, ypos: 10, category: 'actinide', atomic_mass: 232.04 },
  { symbol: 'Pa', name: 'Protactinium', number: 91, xpos: 5, ypos: 10, category: 'actinide', atomic_mass: 231.04 },
  { symbol: 'U', name: 'Uranium', number: 92, xpos: 6, ypos: 10, category: 'actinide', atomic_mass: 238.03 },
  { symbol: 'Np', name: 'Neptunium', number: 93, xpos: 7, ypos: 10, category: 'actinide', atomic_mass: 237 },
  { symbol: 'Pu', name: 'Plutonium', number: 94, xpos: 8, ypos: 10, category: 'actinide', atomic_mass: 244 },
  { symbol: 'Am', name: 'Americium', number: 95, xpos: 9, ypos: 10, category: 'actinide', atomic_mass: 243 },
  { symbol: 'Cm', name: 'Curium', number: 96, xpos: 10, ypos: 10, category: 'actinide', atomic_mass: 247 },
  { symbol: 'Bk', name: 'Berkelium', number: 97, xpos: 11, ypos: 10, category: 'actinide', atomic_mass: 247 },
  { symbol: 'Cf', name: 'Californium', number: 98, xpos: 12, ypos: 10, category: 'actinide', atomic_mass: 251 },
  { symbol: 'Es', name: 'Einsteinium', number: 99, xpos: 13, ypos: 10, category: 'actinide', atomic_mass: 252 },
  { symbol: 'Fm', name: 'Fermium', number: 100, xpos: 14, ypos: 10, category: 'actinide', atomic_mass: 257 },
  { symbol: 'Md', name: 'Mendelevium', number: 101, xpos: 15, ypos: 10, category: 'actinide', atomic_mass: 258 },
  { symbol: 'No', name: 'Nobelium', number: 102, xpos: 16, ypos: 10, category: 'actinide', atomic_mass: 259 },
  { symbol: 'Lr', name: 'Lawrencium', number: 103, xpos: 17, ypos: 10, category: 'actinide', atomic_mass: 266 },
  { symbol: 'Rf', name: 'Rutherfordium', number: 104, xpos: 4, ypos: 7, category: 'transition metal', atomic_mass: 267 },
  { symbol: 'Db', name: 'Dubnium', number: 105, xpos: 5, ypos: 7, category: 'transition metal', atomic_mass: 268 },
  { symbol: 'Sg', name: 'Seaborgium', number: 106, xpos: 6, ypos: 7, category: 'transition metal', atomic_mass: 269 },
  { symbol: 'Bh', name: 'Bohrium', number: 107, xpos: 7, ypos: 7, category: 'transition metal', atomic_mass: 270 },
  { symbol: 'Hs', name: 'Hassium', number: 108, xpos: 8, ypos: 7, category: 'transition metal', atomic_mass: 277 },
  { symbol: 'Mt', name: 'Meitnerium', number: 109, xpos: 9, ypos: 7, category: 'transition metal', atomic_mass: 278 },
  { symbol: 'Ds', name: 'Darmstadtium', number: 110, xpos: 10, ypos: 7, category: 'transition metal', atomic_mass: 281 },
  { symbol: 'Rg', name: 'Roentgenium', number: 111, xpos: 11, ypos: 7, category: 'transition metal', atomic_mass: 282 },
  { symbol: 'Cn', name: 'Copernicium', number: 112, xpos: 12, ypos: 7, category: 'transition metal', atomic_mass: 285 },
  { symbol: 'Nh', name: 'Nihonium', number: 113, xpos: 13, ypos: 7, category: 'post-transition metal', atomic_mass: 286 },
  { symbol: 'Fl', name: 'Flerovium', number: 114, xpos: 14, ypos: 7, category: 'post-transition metal', atomic_mass: 289 },
  { symbol: 'Mc', name: 'Moscovium', number: 115, xpos: 15, ypos: 7, category: 'post-transition metal', atomic_mass: 290 },
  { symbol: 'Lv', name: 'Livermorium', number: 116, xpos: 16, ypos: 7, category: 'post-transition metal', atomic_mass: 293 },
  { symbol: 'Ts', name: 'Tennessine', number: 117, xpos: 17, ypos: 7, category: 'nonmetal', atomic_mass: 294 },
  { symbol: 'Og', name: 'Oganesson', number: 118, xpos: 18, ypos: 7, category: 'noble gas', atomic_mass: 294 }
]
